stale.book.months=6
book.requests.auto_complete.on.add_to_stock=false

data.store.path=data/library.json
csv.export.models=data/exports/books.csv
csv.export.orders=data/exports/orders.csv
csv.import.models=data/imports/books.csv
csv.import.orders=data/imports/orders.csv

db.url=${DB_WEB_URL:jdbc:postgresql://localhost:5433/bookstore_db}
db.user=postgres
db.password=psql_password

hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=validate

secrets.public_key=${SECRETS_DOCKER_PUBLIC_KEY:C:/Users/user/Projects/LibrarySystem/library-system-backend/data/secrets/public.pem}
secrets.private_key=${SECRETS_DOCKER_PRIVATE_KEY:C:/Users/user/Projects/LibrarySystem/library-system-backend/data/secrets/private.pem}

jwt.expiration=PT15M
jwt.refresh-token.expiration=P30D
booking.expires-minutes=15

bank.base.url=${BANK_BASE_URL:http://localhost:8000}
bank.public.base.url=${BANK_PUBLIC_BASE_URL:http://localhost:8080}

app.admin.email=admin@ya.ru
app.admin.password=12345