stale.book.months=6
book.requests.auto_complete.on.add_to_stock=false
data.store.path=data/library.json
csv.export.models=data/exports/books.csv
csv.export.orders=data/exports/orders.csv
csv.import.models=data/imports/books.csv
csv.import.orders=data/imports/orders.csv
db.url=jdbc:postgresql://localhost:5433/bookstore_db
db.user=postgres
db.password=psql_password
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=create